spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
server:
  port: 8080