spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://postgres:5432/event_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082